//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCServiceConsoleClient.CustomerContactServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/ABCServices")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime JoiningDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime JoiningDate {
            get {
                return this.JoiningDateField;
            }
            set {
                if ((this.JoiningDateField.Equals(value) != true)) {
                    this.JoiningDateField = value;
                    this.RaisePropertyChanged("JoiningDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CustomerContactServiceReference.ICustomerContact")]
    public interface ICustomerContact {
        
        // CODEGEN: Generating message contract since message http://tempuri.org/ICustomerContact/GetCustomerContactData requires protection.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContact/GetCustomerContactData", ReplyAction="http://tempuri.org/ICustomerContact/GetCustomerContactDataResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="http://tempuri.org/ICustomerContact/GetCustomerContactDataStringFault", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Name="string", Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactResponse GetCustomerContactData(ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICustomerContact/GetCustomerContactData", ReplyAction="http://tempuri.org/ICustomerContact/GetCustomerContactDataResponse")]
        System.Threading.Tasks.Task<ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactResponse> GetCustomerContactDataAsync(ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerContactRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true, ProtectionLevel=System.Net.Security.ProtectionLevel.None)]
    public partial class CustomerContactRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
        public string LicenceKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", ProtectionLevel=System.Net.Security.ProtectionLevel.None, Order=0)]
        public int CustomerId;
        
        public CustomerContactRequest() {
        }
        
        public CustomerContactRequest(string LicenceKey, int CustomerId) {
            this.LicenceKey = LicenceKey;
            this.CustomerId = CustomerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CustomerContactResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true, ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign)]
    public partial class CustomerContactResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="batatawada.com", ProtectionLevel=System.Net.Security.ProtectionLevel.EncryptAndSign, Order=0)]
        public ABCServiceConsoleClient.CustomerContactServiceReference.Customer MyContact;
        
        public CustomerContactResponse() {
        }
        
        public CustomerContactResponse(ABCServiceConsoleClient.CustomerContactServiceReference.Customer MyContact) {
            this.MyContact = MyContact;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICustomerContactChannel : ABCServiceConsoleClient.CustomerContactServiceReference.ICustomerContact, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerContactClient : System.ServiceModel.ClientBase<ABCServiceConsoleClient.CustomerContactServiceReference.ICustomerContact>, ABCServiceConsoleClient.CustomerContactServiceReference.ICustomerContact {
        
        public CustomerContactClient() {
        }
        
        public CustomerContactClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerContactClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerContactClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerContactClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactResponse ABCServiceConsoleClient.CustomerContactServiceReference.ICustomerContact.GetCustomerContactData(ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest request) {
            return base.Channel.GetCustomerContactData(request);
        }
        
        public ABCServiceConsoleClient.CustomerContactServiceReference.Customer GetCustomerContactData(string LicenceKey, int CustomerId) {
            ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest inValue = new ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest();
            inValue.LicenceKey = LicenceKey;
            inValue.CustomerId = CustomerId;
            ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactResponse retVal = ((ABCServiceConsoleClient.CustomerContactServiceReference.ICustomerContact)(this)).GetCustomerContactData(inValue);
            return retVal.MyContact;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactResponse> ABCServiceConsoleClient.CustomerContactServiceReference.ICustomerContact.GetCustomerContactDataAsync(ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest request) {
            return base.Channel.GetCustomerContactDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactResponse> GetCustomerContactDataAsync(string LicenceKey, int CustomerId) {
            ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest inValue = new ABCServiceConsoleClient.CustomerContactServiceReference.CustomerContactRequest();
            inValue.LicenceKey = LicenceKey;
            inValue.CustomerId = CustomerId;
            return ((ABCServiceConsoleClient.CustomerContactServiceReference.ICustomerContact)(this)).GetCustomerContactDataAsync(inValue);
        }
    }
}
