//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionServiceClient.CreditServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CreditServiceReference.ICreditService")]
    public interface ICreditService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/PerformCreditTransaction", ReplyAction="http://tempuri.org/ICreditService/PerformCreditTransactionResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        bool PerformCreditTransaction(string accountId, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICreditService/PerformCreditTransaction", ReplyAction="http://tempuri.org/ICreditService/PerformCreditTransactionResponse")]
        System.Threading.Tasks.Task<bool> PerformCreditTransactionAsync(string accountId, double amount);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICreditServiceChannel : TransactionServiceClient.CreditServiceReference.ICreditService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditServiceClient : System.ServiceModel.ClientBase<TransactionServiceClient.CreditServiceReference.ICreditService>, TransactionServiceClient.CreditServiceReference.ICreditService {
        
        public CreditServiceClient() {
        }
        
        public CreditServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PerformCreditTransaction(string accountId, double amount) {
            return base.Channel.PerformCreditTransaction(accountId, amount);
        }
        
        public System.Threading.Tasks.Task<bool> PerformCreditTransactionAsync(string accountId, double amount) {
            return base.Channel.PerformCreditTransactionAsync(accountId, amount);
        }
    }
}
