//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransactionServiceClient.DebitServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DebitServiceReference.IDebitService")]
    public interface IDebitService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebitService/PerformDebitTransaction", ReplyAction="http://tempuri.org/IDebitService/PerformDebitTransactionResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Mandatory)]
        bool PerformDebitTransaction(string accountId, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebitService/PerformDebitTransaction", ReplyAction="http://tempuri.org/IDebitService/PerformDebitTransactionResponse")]
        System.Threading.Tasks.Task<bool> PerformDebitTransactionAsync(string accountId, double amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebitService/GetAccountBalance", ReplyAction="http://tempuri.org/IDebitService/GetAccountBalanceResponse")]
        decimal GetAccountBalance(int accountId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDebitService/GetAccountBalance", ReplyAction="http://tempuri.org/IDebitService/GetAccountBalanceResponse")]
        System.Threading.Tasks.Task<decimal> GetAccountBalanceAsync(int accountId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDebitServiceChannel : TransactionServiceClient.DebitServiceReference.IDebitService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DebitServiceClient : System.ServiceModel.ClientBase<TransactionServiceClient.DebitServiceReference.IDebitService>, TransactionServiceClient.DebitServiceReference.IDebitService {
        
        public DebitServiceClient() {
        }
        
        public DebitServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DebitServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DebitServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DebitServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool PerformDebitTransaction(string accountId, double amount) {
            return base.Channel.PerformDebitTransaction(accountId, amount);
        }
        
        public System.Threading.Tasks.Task<bool> PerformDebitTransactionAsync(string accountId, double amount) {
            return base.Channel.PerformDebitTransactionAsync(accountId, amount);
        }
        
        public decimal GetAccountBalance(int accountId) {
            return base.Channel.GetAccountBalance(accountId);
        }
        
        public System.Threading.Tasks.Task<decimal> GetAccountBalanceAsync(int accountId) {
            return base.Channel.GetAccountBalanceAsync(accountId);
        }
    }
}
